language: python
install:
  - pip install tox 
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py31
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=py34    
script:
    - tox -e $TOX_ENV
